"""Build a sampled AhinLendor state from one sanitized referee Observation.

This module accepts only the versioned observation JSON. It does not accept a
referee GameState, deck order, RNG state, or private opponent card identity.
"""
from __future__ import annotations

import random
from typing import Any, Mapping

try:
    from .adapter import AdapterError, NOBLE_IDS_AHINLENDOR
except ImportError:  # Direct unittest/script execution from this directory.
    from adapter import AdapterError, NOBLE_IDS_AHINLENDOR

SCHEMA = "ahin-referee-observation-v1"
CARD_TIERS = tuple((range(1, 41), range(41, 71), range(71, 91)))
TOKEN_NAMES = ("white", "blue", "green", "red", "black", "joker")
BONUS_NAMES = TOKEN_NAMES[:5]
_TOP_LEVEL = {
    "schema", "turn_id", "decision_id", "pending_card_id", "viewer", "current", "count", "phase",
    "final_round", "turns", "bank", "market", "remaining", "nobles",
    "players", "legal_actions", "terminal",
}
_PLAYER_FIELDS = {"tokens", "bonuses", "score", "owned_card_ids", "nobles", "reserved"}
_RESERVED_FIELDS = {"card_id", "tier", "public"}
_PHASES = {"main", "payment", "return", "noble", "terminal"}


def _integer(value: Any, name: str, minimum: int = 0, maximum: int | None = None) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise AdapterError(f"{name} must be an integer")
    if value < minimum or (maximum is not None and value > maximum):
        raise AdapterError(f"{name} is outside its allowed range")
    return value


def _vector(value: Any, size: int, name: str, maximum: int | None = None) -> tuple[int, ...]:
    if not isinstance(value, (list, tuple)) or len(value) != size:
        raise AdapterError(f"{name} must contain exactly {size} integers")
    return tuple(_integer(item, f"{name}[{index}]", maximum=maximum)
                 for index, item in enumerate(value))


def _token_dict(values: tuple[int, ...], names: tuple[str, ...]) -> dict[str, int]:
    return dict(zip(names, values, strict=True))


def _card_id(value: Any, name: str) -> int:
    return _integer(value, name, 0, 89) + 1


def _noble_id(value: Any, name: str) -> int:
    canonical = _integer(value, name, 0, 9)
    return NOBLE_IDS_AHINLENDOR[canonical]


def _unique(values: list[int], name: str) -> None:
    if len(values) != len(set(values)):
        raise AdapterError(f"duplicate identity in {name}")


def build_load_state_payload(observation: Mapping[str, Any], *, sample_seed: int) -> dict[str, Any]:
    """Return an Ahin NativeEnv.load_state payload sampled from public input.

    `sample_seed` selects a reproducible hidden-card assignment and draw order.
    It must be generated by the caller's agent RNG, not copied from the referee.
    """
    if not isinstance(observation, Mapping):
        raise AdapterError("observation must be a mapping")
    extra = set(observation) - _TOP_LEVEL
    missing = _TOP_LEVEL - set(observation)
    if extra:
        raise AdapterError(f"unexpected observation fields: {sorted(extra)}")
    if missing:
        raise AdapterError(f"missing observation fields: {sorted(missing)}")
    if observation["schema"] != SCHEMA:
        raise AdapterError("unsupported referee observation schema")
    _integer(sample_seed, "sample_seed", 0, 2**64 - 1)
    turns = _integer(observation["turns"], "turns")
    turn_id = _integer(observation["turn_id"], "turn_id")
    decision_id = _integer(observation["decision_id"], "decision_id")
    if turn_id != turns:
        raise AdapterError("turn_id must identify the canonical full-turn clock")

    count = _integer(observation["count"], "count", 2, 2)
    viewer = _integer(observation["viewer"], "viewer", 0, 1)
    current = _integer(observation["current"], "current", 0, 1)
    if current != viewer:
        raise AdapterError("Ahin state must be hydrated for the acting viewer")
    phase = observation["phase"]
    if not isinstance(phase, str) or phase not in _PHASES:
        raise AdapterError("unknown canonical phase")
    pending_card = observation["pending_card_id"]
    if phase == "payment":
        if pending_card is None:
            raise AdapterError("payment phase requires its pending card identity")
        _card_id(pending_card, "pending_card_id")
    elif pending_card is not None:
        raise AdapterError("pending_card_id is only valid in payment phase")
    if phase in {"payment", "terminal"}:
        raise AdapterError(f"Ahin search cannot start in {phase} phase")
    if observation["terminal"] is not False:
        raise AdapterError("Ahin search accepts only a nonterminal observation")
    if not isinstance(observation["legal_actions"], (list, tuple)):
        raise AdapterError("legal_actions must be a list")
    if not isinstance(observation["final_round"], bool):
        raise AdapterError("final_round must be boolean")

    bank = _vector(observation["bank"], 6, "bank")
    raw_market = observation["market"]
    if not isinstance(raw_market, (list, tuple)) or len(raw_market) != 12:
        raise AdapterError("market must contain exactly 12 card IDs or nulls")
    market = tuple(0 if card is None else _card_id(card, f"market[{i}]")
                   for i, card in enumerate(raw_market))
    remaining = _vector(observation["remaining"], 3, "remaining", 36)
    if any(remaining[i] > (36, 26, 16)[i] for i in range(3)):
        raise AdapterError("remaining draw pile exceeds its initial size")

    raw_nobles = observation["nobles"]
    if not isinstance(raw_nobles, (list, tuple)) or len(raw_nobles) > 3:
        raise AdapterError("nobles must contain at most three visible IDs")
    nobles = [_noble_id(value, f"nobles[{i}]") for i, value in enumerate(raw_nobles)]
    _unique(nobles, "available nobles")

    raw_players = observation["players"]
    if not isinstance(raw_players, (list, tuple)) or len(raw_players) != count:
        raise AdapterError("players must contain one entry per active seat")
    players: list[dict[str, Any]] = []
    used_cards: set[int] = set()
    owned_nobles: set[int] = set()
    hidden_by_tier = [0, 0, 0]
    pending_hidden: list[tuple[int, int]] = []
    all_cards_by_tier = [set(row) for row in CARD_TIERS]

    # Reserve public and purchased identities before sampling any hidden cards.
    for player_index, raw_player in enumerate(raw_players):
        if not isinstance(raw_player, Mapping):
            raise AdapterError(f"players[{player_index}] must be an object")
        if set(raw_player) != _PLAYER_FIELDS:
            raise AdapterError(f"players[{player_index}] has fields outside the referee schema")
        tokens = _vector(raw_player["tokens"], 6, f"players[{player_index}].tokens")
        bonuses = _vector(raw_player["bonuses"], 5, f"players[{player_index}].bonuses")
        score = _integer(raw_player["score"], f"players[{player_index}].score")
        owned_raw = raw_player["owned_card_ids"]
        if not isinstance(owned_raw, (list, tuple)):
            raise AdapterError("owned_card_ids must be a list")
        owned = [_card_id(card, f"players[{player_index}].owned_card_ids") for card in owned_raw]
        for card in owned:
            if card in used_cards:
                raise AdapterError("duplicate card identity in observation")
            used_cards.add(card)
        raw_claimed = raw_player["nobles"]
        if not isinstance(raw_claimed, (list, tuple)):
            raise AdapterError("player nobles must be a list")
        claimed = [_noble_id(value, f"players[{player_index}].nobles") for value in raw_claimed]
        for noble in claimed:
            if noble in owned_nobles or noble in nobles:
                raise AdapterError("duplicate noble identity in observation")
            owned_nobles.add(noble)

        raw_reserved = raw_player["reserved"]
        if not isinstance(raw_reserved, (list, tuple)) or len(raw_reserved) > 3:
            raise AdapterError("each player can reserve at most three cards")
        reserved_items: list[dict[str, Any] | None] = []
        for slot_index, raw_slot in enumerate(raw_reserved):
            if not isinstance(raw_slot, Mapping) or set(raw_slot) != _RESERVED_FIELDS:
                raise AdapterError("reserved item must match the public observation schema")
            tier = _integer(raw_slot["tier"], "reserved tier", 0, 2)
            is_public = raw_slot["public"]
            if not isinstance(is_public, bool):
                raise AdapterError("reserved public flag must be boolean")
            raw_card = raw_slot["card_id"]
            is_viewer = player_index == viewer
            if raw_card is None:
                if is_viewer or is_public:
                    raise AdapterError("viewer/public reservation identity must be known")
                hidden_by_tier[tier] += 1
                pending_hidden.append((player_index, slot_index))
                reserved_items.append(None)
                continue
            if (not is_viewer) and not is_public:
                raise AdapterError("opponent blind reservation identity must be hidden")
            card = _card_id(raw_card, "reserved card_id")
            if card not in all_cards_by_tier[tier]:
                raise AdapterError("reserved card ID does not match its tier")
            if card in used_cards:
                raise AdapterError("duplicate card identity in observation")
            used_cards.add(card)
            reserved_items.append({"card_id": card, "is_public": is_public})
        players.append({
            "tokens": _token_dict(tokens, TOKEN_NAMES),
            "bonuses": _token_dict(bonuses, BONUS_NAMES),
            "points": score,
            "purchased_card_ids": owned,
            "reserved": reserved_items,
            "claimed_noble_ids": claimed,
        })

    for slot_index, card in enumerate(market):
        if card == 0:
            continue
        tier = slot_index // 4
        if card not in all_cards_by_tier[tier]:
            raise AdapterError("market card ID does not match its tier-major slot")
        if card in used_cards:
            raise AdapterError("duplicate card identity in observation")
        used_cards.add(card)

    # Each hidden reserve consumes one card from the unseen public tier pool.
    # The remaining draw-pile count is public; only identities and order are sampled.
    rng = random.Random(sample_seed)
    deck_by_tier: list[list[int]] = []
    tier_candidates: list[list[int]] = []
    for tier in range(3):
        unseen = sorted(all_cards_by_tier[tier] - used_cards)
        expected_unseen = remaining[tier] + hidden_by_tier[tier]
        if len(unseen) != expected_unseen:
            raise AdapterError(
                f"tier {tier} inventory mismatch: public identities imply {len(unseen)} "
                f"unseen cards, counts require {expected_unseen}"
            )
        tier_candidates.append(unseen)

    for player_index, slot_index in pending_hidden:
        slot = players[player_index]["reserved"][slot_index]
        assert slot is None
        tier = _integer(raw_players[player_index]["reserved"][slot_index]["tier"], "reserved tier", 0, 2)
        choices = tier_candidates[tier]
        picked_at = rng.randrange(len(choices))
        card = choices.pop(picked_at)
        slot = {"card_id": card, "is_public": False}
        players[player_index]["reserved"][slot_index] = slot
        used_cards.add(card)

    for tier in range(3):
        deck = tier_candidates[tier]
        if len(deck) != remaining[tier]:
            raise AdapterError("sampled hidden reservations do not match deck counts")
        rng.shuffle(deck)
        deck_by_tier.append(deck)

    phase_flags = {
        "is_return_phase": phase == "return",
        "is_noble_choice_phase": phase == "noble",
    }
    # Ahin derives the two-player final-round terminal boundary from score,
    # turn owner, and phase. Preserve the referee flag for auditing as well.
    return {
        "current_player": current,
        "move_number": turns,
        "players": players,
        "faceup_card_ids": [list(market[i:i + 4]) for i in (0, 4, 8)],
        "available_noble_ids": nobles,
        "bank": _token_dict(bank, TOKEN_NAMES),
        "phase_flags": phase_flags,
        "deck_card_ids_by_tier": deck_by_tier,
        "metadata": {
            "source_schema": SCHEMA,
            "turn_id": turn_id,
            "decision_id": decision_id,
            "viewer": viewer,
            "final_round": observation["final_round"],
            "phase": phase,
        },
    }
