// Research entry. Vite serves this file in development; the app does not import it.
import { startGpu } from './gpu-client';
// @ts-ignore Generated by the locked wasm-bindgen build.
import init, { WebGame } from '../pkg/splendor_web.js';

self.onmessage = async (event: MessageEvent<{schedule: Array<{id:number; seed:string; seats: [1|2|8, 1|2|8]}>; deadlineEpochMs:number}>) => {
  const stops: Array<() => void> = [];
  try {
    await init();
    const metadata = await (await fetch('/champion.json')).json();
    const backends: Record<number, unknown> = {};
    for (const size of [1, 2, 8] as const) {
      stops.push(await startGpu(metadata.model.sha256, location.origin + '/', error => { throw new Error(error); }, () => {}, size));
      backends[size] = (globalThis as unknown as {splendorInference: unknown}).splendorInference;
    }
    self.postMessage({type:'ready'});
    const config = (size: number) => JSON.stringify({searchAgent:'flywheel-best', gpuInference:true, inferenceBatchSize:size,
      iterations:1000000000, depth:64, worldPool:3, cpuct:.4, fpuReduction:.02965, dynamicFpu:true, chanceUniverses:3,
      uniformPrior:0, rootOnly:false, rootNoise:0});
    for (const item of event.data.schedule) {
      if (Date.now() >= event.data.deadlineEpochMs) break;
      const {id, seed, seats} = item;
      self.postMessage({type:'start',id,seed,seats});
      const games = [0,1].map(seat => new WebGame(seed, 1-seat, new TextEncoder().encode('SPENTY01'), config(seats[seat])));
      let snapshot = JSON.parse(games[0].snapshot());
      const started = performance.now();
      const turns: unknown[] = [];
      let decisions = 0;
      let stopped: string | null = null;
      while (!snapshot.result) {
        if (Date.now()+5000 >= event.data.deadlineEpochMs || performance.now()-started > 480000 || decisions >= 512) { stopped = 'research_limit'; break; }
        const actor = snapshot.activePlayer;
        const size = seats[actor];
        Object.assign(globalThis, {splendorInference:backends[size]});
        const before = JSON.parse(games[actor].searchWork());
        const tick = performance.now();
        let steps = 0;
        do {
          snapshot = JSON.parse(games[actor].botStepWithDeadline(tick+4900));
          const action = snapshot.lastEvents[0].actionId;
          games[1-actor].actOne(action);
          // Compare full state and journals after every checked legal decision.
          const a = JSON.parse(games[0].trainingRecord());
          const b = JSON.parse(games[1].trainingRecord());
          if (a.stateDebug !== b.stateDebug || JSON.stringify(a.actions) !== JSON.stringify(b.actions)) throw new Error('Paired state mismatch');
          decisions++; steps++;
          if (steps > 16) throw new Error('Turn exceeded decision guard');
        } while (!snapshot.result && snapshot.activePlayer === actor);
        const after = JSON.parse(games[actor].searchWork());
        const turn = {actor, batch:size, ms:performance.now()-tick, simulations:after.simulations-before.simulations,
          inferences:after.inferenceCalls-before.inferenceCalls, decisions:steps};
        turns.push(turn);
        self.postMessage({type:'turn',id,seed,seats,turn,turnCount:turns.length,checkpoint:turns.length%10===0 ? JSON.parse(games[0].trainingRecord()) : undefined});
      }
      const replay = JSON.parse(games[0].trainingRecord());
      const record = {id,seed,seats,result:snapshot.result,stopped,turns,replay,elapsedMs:performance.now()-started};
      self.postMessage({type:'game',record});
      for (const game of games) game.free();
    }
    self.postMessage({type:'done'});
  } catch (error) { self.postMessage({type:'error',error:String(error)}); }
  finally { for (const stop of stops) stop(); }
};
