[package]
name = "splendor-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
[features]
default = []
benchmark-compat = []
[dependencies]
arrayvec.workspace = true
[dev-dependencies]
criterion.workspace = true
proptest = "1"
[[bench]]
name = "engine"
harness = false
